"""Explicit agent SELECT contract for V1-V4; never infer access from model SQL.

Update with schema_context and runtime grants when a later migration is approved.
"""

from __future__ import annotations


MAX_ROWS = 200
BLOCKED_COLUMNS = frozenset({"nickname", "raw", "is_ranker"})

TABLE_COLUMNS: dict[str, tuple[str, ...]] = {
    "games": (
        "game_id",
        "season_id",
        "matching_mode",
        "matching_team_mode",
        "version_season",
        "version_major",
        "version_minor",
        "start_dtm",
        "server_name",
        "fetched_at",
        "match_size",
        "team_count",
        "mmr_avg",
        "main_weather",
        "sub_weather",
    ),
    "participants": (
        "game_id",
        "team_number",
        "character_num",
        "best_weapon",
        "best_weapon_level",
        "game_rank",
        "player_kill",
        "player_assistant",
        "monster_kill",
        "damage_to_player",
        "mmr_before",
        "mmr_gain",
        "mmr_after",
        "play_time",
        "participant_id",
        "user_id",
        "version_major",
        "version_minor",
        "tier",
        "tier_division",
        "victory",
        "character_level",
        "skin_code",
        "player_deaths",
        "team_kill",
        "total_field_kill",
        "give_up",
        "escape_state",
        "account_level",
        "mmr_gain_in_game",
        "mmr_loss_entry_cost",
        "gambit",
        "kings_gambit",
        "mmr_gain_gambit",
        "watch_time",
        "total_time",
        "duration",
        "use_emoticon_count",
        "damage_to_player_basic",
        "damage_to_player_skill",
        "damage_to_player_item_skill",
        "damage_to_player_direct",
        "damage_to_monster",
        "damage_from_player",
        "damage_from_player_basic",
        "damage_from_player_skill",
        "damage_from_player_item_skill",
        "damage_from_player_direct",
        "damage_from_monster",
        "damage_offseted_by_shield_player",
        "heal_amount",
        "team_recover",
        "protect_absorb",
        "cc_time_to_player",
        "team_down",
        "team_elimination",
        "terminate_count",
        "clutch_count",
        "kills_phase_one",
        "kills_phase_two",
        "kills_phase_three",
        "deaths_phase_one",
        "deaths_phase_two",
        "deaths_phase_three",
        "credit_revival_count",
        "credit_revived_others_count",
        "max_hp",
        "attack_power",
        "defense",
        "attack_speed",
        "move_speed",
        "skill_amp",
        "adaptive_force",
        "cool_down_reduction",
        "critical_strike_chance",
        "life_steal",
        "attack_range",
        "sight_range",
        "total_gain_vf_credit",
        "total_use_vf_credit",
        "craft_uncommon",
        "craft_rare",
        "craft_epic",
        "craft_legend",
        "craft_mythic",
        "camp_fire_craft_uncommon",
        "camp_fire_craft_rare",
        "camp_fire_craft_epic",
        "camp_fire_craft_legendary",
        "kill_player_gain_vf_credit",
        "kill_chicken_gain_vf_credit",
        "kill_boar_gain_vf_credit",
        "kill_wild_dog_gain_vf_credit",
        "kill_wolf_gain_vf_credit",
        "kill_bear_gain_vf_credit",
        "kill_bat_gain_vf_credit",
        "kill_raven_gain_vf_credit",
        "kill_wickline_gain_vf_credit",
        "kill_alpha_gain_vf_credit",
        "kill_omega_gain_vf_credit",
        "kill_gamma_gain_vf_credit",
        "kill_drone_gain_vf_credit",
        "kill_item_bounty_gain_vf_credit",
        "add_telephoto_camera",
        "remove_telephoto_camera",
        "use_hyper_loop",
        "use_security_console",
        "use_recon_drone",
        "use_emp_drone",
        "tactical_skill_use_count",
        "kill_gamma",
        "enter_dimension_rift",
        "win_from_dimension_rift",
        "enter_dimension_empowered_rift",
        "win_from_dimension_empowered_rift",
        "sum_get_buff_cube",
        "trait_first_core",
        "tactical_skill_group",
        "tactical_skill_level",
        "route_id_of_start",
        "place_of_start",
        "skill_order",
        "total_vf_credits",
        "used_vf_credits",
        "total_tk_per_min",
        "food_craft_count",
        "item_transferred_drone",
        "item_transferred_console",
        "skill_level_info",
        "credit_source",
        "kill_monsters",
    ),
    "characters": (
        "character_code",
        "name_ko",
        "name_en",
    ),
    "weapon_types": (
        "code",
        "name_ko",
    ),
    "tiers": (
        "season_id",
        "tier",
        "division",
        "min_mmr",
        "sort_order",
    ),
    "participant_equipment": (
        "participant_id",
        "kind",
        "slot",
        "item_code",
        "grade",
    ),
    "participant_traits": (
        "participant_id",
        "slot_type",
        "trait_code",
    ),
    "participant_mastery": (
        "participant_id",
        "mastery_code",
        "mastery_level",
    ),
    "participant_matchups": (
        "participant_id",
        "character_num",
        "opponent_character_num",
        "kills",
        "deaths",
    ),
    "participant_deaths": (
        "participant_id",
        "death_seq",
        "killer_type",
        "killer_participant_id",
        "killer_character_num",
        "killer_name",
        "killer_weapon",
        "cause_of_death",
        "place_of_death",
    ),
}

ALLOWED_TABLES = frozenset(TABLE_COLUMNS)
